In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [7]:
sum(a)

14

In [8]:
np_a = np.array(a)

In [10]:
np_b = np.array(b)

In [11]:
np_a + np_b

array([ 5, 17, 34])

In [12]:
p = np.array([1,2,"abc"])

In [13]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [14]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [15]:
np_a.max()

7

In [16]:
np_a.mean()

4.666666666666667

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np_a*np.ones(3)

array([2., 5., 7.])

In [20]:
np_a*[3]

array([ 6, 15, 21])

In [21]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [22]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [23]:
np_a[1]

5

In [24]:
np_a[1:]

array([5, 7])

In [25]:
np_a[0:2]

array([2, 5])

In [27]:
np_2d = np.array([[1,2],[3,4]])

In [28]:
np_2d.sum()

10

In [29]:
np_2d.sum(axis=0)

array([4, 6])

In [30]:
np_2d.sum(axis=1)

array([3, 7])

In [31]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [32]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [34]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [36]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np_2d

array([[1, 2],
       [3, 4]])

In [38]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [39]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [41]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [43]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [44]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [45]:
np_dotp[0,1]

210

In [46]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [47]:
np_dotp[0:2,0]

array([2001, 4003])

In [48]:
np_rs = np.array([1,2,3,4,5,6])

In [49]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [50]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [54]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [57]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.random(2)

TypeError: 'module' object is not callable

In [59]:
np.random.random(2)

array([0.43365602, 0.67705795])

In [60]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [61]:
import numpy.random as random

In [62]:
random(2)

TypeError: 'module' object is not callable

In [63]:
random.random(2)

array([0.26399133, 0.7125254 ])

In [65]:
random.random([3,2])

array([[0.30526688, 0.41513002],
       [0.598052  , 0.11485611],
       [0.0684223 , 0.54712717]])

In [66]:
import numpy.linalg as la

In [67]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
la.eig(np_2d)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [70]:
la.svd(np_2d)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [71]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [75]:
random.rand(2,3)*5

array([[1.91814336, 3.3888604 , 1.73449056],
       [4.35126763, 2.85394498, 4.83614907]])

In [74]:
random.randn(2,3)

array([[-1.23473641,  1.20362352, -0.0691662 ],
       [ 0.0334294 ,  1.00109125, -0.22592634]])

In [76]:
random.randint(-2,3,5)

array([ 1, -1, -2,  2,  0])

In [77]:
random.shuffle(np_rs)

In [78]:
np_rs

array([3, 6, 4, 1, 2, 5])

In [79]:
random.choice(np_rs, 2)

array([1, 6])

In [80]:
random.binomial(20,0.3)

5

In [81]:
random.binomial(20, 0.3, 7)

array([ 5,  8,  2,  7,  7, 10,  4])

In [82]:
random.exponential(0.7,4)

array([0.13372559, 0.62232793, 1.1424338 , 0.36568844])

In [ ]:
%%time


In [83]:
random.normal(-5,12,3)

array([-13.16651465,  -0.12575013,  -1.52670445])

In [84]:
random.logistic(-2,4,7)

array([-13.86959627,  -6.28421112,  -2.89562533,  -2.56350521,
         3.03949534,  -9.1472225 ,   6.53402689])

In [85]:
np_2d.shape

(2, 2)

In [86]:
np_2d.dtype

dtype('int32')

In [87]:
type(np_2d)

numpy.ndarray

In [90]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [94]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [95]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [96]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [97]:
np_x = np.array(x)
np_y = np.array(y)

In [100]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


Wall time: 1.96 s


In [99]:
%%time
np_z = np_x+np_y

Wall time: 32.9 ms


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('NumpyExerciseData.csv')
print(df.head(5))
print(df.shape)

   X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0   1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1   1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2   1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3   1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4   1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   

   Unnamed: 10  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
(50, 11)


In [4]:

np_Arr = df.to_numpy()
np_Arr.shape
#Train-test Split
train_X = np_Arr[:42,0:6] #X Values
train_Y = np_Arr[:42,6:7] #y column
print("X-Train : ",train_X.shape)
print("Y-Train : ",train_Y.shape)

test_X = np_Arr[43:,0:6] 
test_Y = np_Arr[43:,6:7]
print("X-Test : ",test_X.shape)
print("X-Test : ",test_Y.shape)
# Taking Transpose
train_Trans = train_X.transpose()
print(train_Trans.shape)
test_Trans = test_X.transpose()
print(test_Trans.shape)
#Inverse
train_Inv = np.linalg.inv(np.dot(train_Trans,train_X))
train_Inv.shape
# ((X'X)^-1)*X'y
weights = np.dot(train_Inv,np.dot(train_Trans,train_Y))
weights
print(train_Trans.shape)
print(train_Inv.shape)
print(train_Y.shape)
y_Train_Pred = np.dot(train_X,weights)
y_Test_Pred = np.dot(test_X,weights)
print(y_Train_Pred)
print(y_Test_Pred)
#Error Computation (both Training and Test Error) Generate y values from the new generated w values Compute the SSR, MSR and RMSE between the generated y values and 
#the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51
newt_ssr_train = np.sum(np.power(np.subtract(train_Y,y_Train_Pred),2))
newt_ssr_test = np.sum(np.power(np.subtract(test_Y,y_Test_Pred),2))
print("SSR - Newton's Method (Train) : ",newt_ssr_train)
print("SSR - Newton's Method (Test) : ",newt_ssr_test)


X-Train :  (42, 6)
Y-Train :  (42, 1)
X-Test :  (7, 6)
X-Test :  (7, 1)
(6, 42)
(6, 7)
(6, 42)
(6, 6)
(42, 1)
[[27.99735178]
 [46.0019147 ]
 [14.28976738]
 [17.04177241]
 [31.67075174]
 [ 8.30314785]
 [30.04695842]
 [22.233347  ]
 [23.68180355]
 [23.84690947]
 [42.76729129]
 [30.35482768]
 [19.75303311]
 [ 2.06200743]
 [18.9159862 ]
 [24.21134276]
 [22.29832155]
 [22.41862645]
 [24.40448903]
 [23.34613623]
 [33.66856162]
 [19.09487106]
 [46.26184153]
 [25.83254426]
 [28.30481522]
 [27.99226972]
 [32.63972557]
 [27.55867831]
 [22.40435261]
 [32.98528128]
 [28.17253988]
 [19.69745273]
 [25.09008735]
 [27.81587681]
 [31.43799708]
 [33.12878759]
 [41.02761124]
 [32.24662927]
 [33.04960476]
 [36.12795901]
 [58.01542692]
 [ 4.80130013]]
[[ 9.65564574]
 [20.19281545]
 [ 5.48013131]
 [27.92782592]
 [-0.7097756 ]
 [24.80331676]
 [33.47021636]]
SSR - Newton's Method (Train) :  2.9540159678699305
SSR - Newton's Method (Test) :  0.8348154155610092


In [5]:
# MSR and RMSE
newt_msr_train = np.mean(np.power(np.subtract(train_Y,y_Train_Pred),2))
newt_msr_test = np.mean(np.power(np.subtract(test_Y,y_Test_Pred),2))
print("MSR - Newton's Method (Train) : ",newt_msr_train)
print("MSR - Newton's Method (Test) : ",newt_msr_test)

MSR - Newton's Method (Train) :  0.07033371352071263
MSR - Newton's Method (Test) :  0.11925934508014417


In [6]:
newt_rmse_train = np.sqrt(newt_msr_train)
newt_rmse_test = np.sqrt(newt_msr_test)
print("RMSE - Newton's Method (Train) : ",newt_rmse_train)
print("RMSE - Newton's Method (Test) : ",newt_rmse_test)

RMSE - Newton's Method (Train) :  0.2652050405265945
RMSE - Newton's Method (Test) :  0.3453394635429669


In [ ]:
#Regularized Newton Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41 Use lambda as 0.17 Compute andreport both training and test errors for the regularized newton computation

In [8]:
# ((X'X+lambda*I)^-1)*X'y
reg_Newt_Train_W = np.dot(np.linalg.inv(np.add(np.dot(train_Trans,train_X),np.dot(0.17,np.identity(train_X.shape[1])))),np.dot(train_Trans,train_Y))
reg_Newt_Train_W
print("Regularized Newton's Method - Weights : ",reg_Newt_Train_W)

Regularized Newton's Method - Weights :  [[-6.76458303]
 [ 3.23443812]
 [ 0.15156595]
 [11.6759603 ]
 [ 0.37862746]
 [-1.5650966 ]]


In [10]:
y_Reg_Newt_Train_Pred = np.dot(train_X,reg_Newt_Train_W)
y_Reg_Newt_Test_Pred = np.dot(test_X,reg_Newt_Train_W)
print("Y - Prediction - Regularized Newton's Method : ",y_Reg_Newt_Train_Pred)
print("Y - Prediction - Regularized Newton's Method : ",y_Reg_Newt_Test_Pred)


Y - Prediction - Regularized Newton's Method :  [[27.90442388]
 [45.67481598]
 [14.65825923]
 [17.22958364]
 [31.93986893]
 [ 8.61908135]
 [30.22704069]
 [22.51506218]
 [23.8710003 ]
 [23.78110841]
 [42.87980875]
 [30.62524582]
 [20.0686052 ]
 [ 2.41670754]
 [18.91936626]
 [24.49402371]
 [22.25422863]
 [22.2941932 ]
 [24.61386666]
 [23.25607865]
 [33.56940962]
 [19.33537669]
 [45.94873213]
 [25.5676731 ]
 [28.21586557]
 [28.11539999]
 [32.77039794]
 [27.57238841]
 [22.51395146]
 [32.74365814]
 [28.22531596]
 [19.87890057]
 [24.99005401]
 [27.85594388]
 [31.66235042]
 [33.04763956]
 [40.40106368]
 [32.16488068]
 [32.87774233]
 [35.80368785]
 [57.64805792]
 [ 4.99912022]]
Y - Prediction - Regularized Newton's Method :  [[10.07701936]
 [20.43815661]
 [ 5.73100093]
 [27.68196849]
 [-0.41919772]
 [25.1088653 ]
 [33.63316198]]


In [ ]:
#Compute R-squared values for both Newton and Regularized Newton on both train and test datasets Look up how to compute R-squared values in excel

In [11]:
ssr_reg_train= np.sum(np.power(np.subtract(train_Y,y_Reg_Newt_Train_Pred),2))
ssr_reg_test = np.sum(np.power(np.subtract(test_Y,y_Reg_Newt_Test_Pred),2))
print("SSR - Regularized Newton's Method (Train) : ",ssr_reg_train)
print("SSR - Regularized Newton's Method (Test) : ",ssr_reg_test)

SSR - Regularized Newton's Method (Train) :  5.1842062198156995
SSR - Regularized Newton's Method (Test) :  0.8551708105164015


In [12]:
sst_train = np.sum(np.power(train_Y-np.mean(train_Y),2))
sst_test = np.sum(np.power(test_Y-np.mean(test_Y),2))
print("SST - Regularized Newton's Method (Train) : ",sst_train)
print("SST - Regularized Newton's Method (Test) : ",sst_test)


SST - Regularized Newton's Method (Train) :  4605.071428571428
SST - Regularized Newton's Method (Test) :  975.7142857142856


In [13]:
R_squared_Newt_Train = 1 - (newt_ssr_train / sst_train) #For Newton Train Set
R_squared_Newt_Test = 1 - (newt_ssr_test / sst_test) 
print("R-Squared - Newton's Method (Train) : ",R_squared_Newt_Train)
print("R-Squared - Newton's Method (Test) : ",R_squared_Newt_Test)

R-Squared - Newton's Method (Train) :  0.9993585298265859
R-Squared - Newton's Method (Test) :  0.9991444058698496


In [14]:
R_squared_Newt_Reg_Train= 1 - (ssr_reg_train / sst_train) #For Regularized Newton Train Set
R_squared_Newt_Reg_Test = 1 - (ssr_reg_test / sst_test)
print("R-Squared - Regularized Newton's Method (Train) : ",R_squared_Newt_Reg_Train)
print("R-Squared - Regularized Newton's Method (Test) : ",R_squared_Newt_Reg_Test)


R-Squared - Regularized Newton's Method (Train) :  0.9988742397810269
R-Squared - Regularized Newton's Method (Test) :  0.9991235438252394


Let's try some more things For each of the below report the following, MSR on train, MSR on test, R-squared on train and R-squared on test

Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83
Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17
Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83
Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17
Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83

In [15]:
lambda_Arr = np.array([0.83,0.17,0.83,0.17,0.83])
new_Dict = {0:[2,41,42,51],1:[2,26,27,51],2:[2,26,27,51],3:[2,11,12,51],4:[2,11,12,51]}
for i in range(len(lambda_Arr)):
    print("For lambda : ",lambda_Arr[i])
    train_Arr = np_Arr[:new_Dict[i][1]+1,0:6] #X Values
    train_Y = np_Arr[:new_Dict[i][1]+1,6:7] #y column
    test_Arr = np_Arr[new_Dict[i][2]:new_Dict[i][3]+1,0:6] 
    test_Y = np_Arr[new_Dict[i][2]:new_Dict[i][3]+1,6:7]
    train_Trans = train_Arr.transpose()
    test_Trans = test_Arr.transpose()
    print(train_Trans.shape)
    print(train_Arr.shape)
    train_Inv = np.linalg.inv(np.dot(train_Trans,train_Arr))
    w = np.dot(train_Inv,np.dot(train_Trans,train_Y))
    y_Train_Pred = np.dot(train_Arr,w)
    y_Test_Pred = np.dot(test_Arr,w)
    newt_ssr_train = np.sum(np.power(np.subtract(train_Y,y_Train_Pred),2))
    newt_ssr_test = np.sum(np.power(np.subtract(test_Y,y_Test_Pred),2))
    newt_msr_train = np.mean(np.power(np.subtract(train_Y,y_Train_Pred),2))
    newt_msr_test = np.mean(np.power(np.subtract(test_Y,y_Test_Pred),2))
    print("MSR - Newton's Method (Train) : ",newt_msr_train)
    print("MSR - Newton's Method (Test) : ",newt_msr_test)
    newt_rmse_train = np.sqrt(newt_msr_train)
    newt_rmse_test = np.sqrt(newt_msr_test)
    reg_Newt_Train_W = np.dot(np.linalg.inv(np.add(np.dot(train_Trans,train_Arr),np.dot(lambda_Arr[i],np.identity(train_Arr.shape[1])))),np.dot(train_Trans,train_Y))
    y_Reg_Newt_Train_Pred = np.dot(train_Arr,reg_Newt_Train_W)
    y_Reg_Newt_Test_Pred = np.dot(test_Arr,reg_Newt_Train_W)
    ssr_reg_train= np.sum(np.power(np.subtract(train_Y,y_Reg_Newt_Train_Pred),2))
    ssr_reg_test = np.sum(np.power(np.subtract(test_Y,y_Reg_Newt_Test_Pred),2))
    sst_train = np.sum(np.power(train_Y-np.mean(train_Y),2))
    sst_test = np.sum(np.power(test_Y-np.mean(test_Y),2))
    R_squared_Newt_Train = 1 - (newt_ssr_train / sst_train) #For Newton Train Set
    R_squared_Newt_Test = 1 - (newt_ssr_test / sst_test) 
    print("R-Squared - Newton's Method (Train) : ",R_squared_Newt_Train)
    print("R-Squared - Newton's Method (Test) : ",R_squared_Newt_Test)
    R_squared_Newt_Reg_Train= 1 - (ssr_reg_train / sst_train) #For Regularized Newton Train Set
    R_squared_Newt_Reg_Test = 1 - (ssr_reg_test / sst_test)
    print("R-Squared - Regularized Newton's Method (Train) : ",R_squared_Newt_Reg_Train)
    print("R-Squared - Regularized Newton's Method (Test) : ",R_squared_Newt_Reg_Test)

For lambda :  0.83
(6, 42)
(42, 6)
MSR - Newton's Method (Train) :  0.07033371352071263
MSR - Newton's Method (Test) :  0.10619375965192485
R-Squared - Newton's Method (Train) :  0.9993585298265859
R-Squared - Newton's Method (Test) :  0.9992226466181261
R-Squared - Regularized Newton's Method (Train) :  0.9928913107550846
R-Squared - Regularized Newton's Method (Test) :  0.9936205259861491
For lambda :  0.17
(6, 27)
(27, 6)
MSR - Newton's Method (Train) :  0.05963269971571594
MSR - Newton's Method (Test) :  0.19537189790600548
R-Squared - Newton's Method (Train) :  0.9993804196155756
R-Squared - Newton's Method (Test) :  0.9987379199659021
R-Squared - Regularized Newton's Method (Train) :  0.997920207650558
R-Squared - Regularized Newton's Method (Test) :  0.9985558154198331
For lambda :  0.83
(6, 27)
(27, 6)
MSR - Newton's Method (Train) :  0.05963269971571594
MSR - Newton's Method (Test) :  0.19537189790600548
R-Squared - Newton's Method (Train) :  0.9993804196155756
R-Squared - New

LinAlgError: Singular matrix

In [ ]:
#A square matrix that does not have a matrix inverse.
#A matrix is singular iff its determinant is 0
